### ISSUE TITLE
Segmentation fault inside Docker

### ISSUE THREAD

**Issue by dup2** [ankane/isotree#3]
Hi

Thanks for the great library.

Running inside docker, I get a segmentation fault.

Ruby 2.7.5p203
Docker image based on ubuntu 18.04
libomp5:amd64               5.0.1-1                             amd64        LLVM OpenMP runtime

```
/bundle/ruby/2.7.0/gems/isotree-0.2.1/lib/isotree/isolation_forest.rb:47: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0040 p:---- s:0219 e:000218 CFUNC  :fit_iforest
c:0039 p:0071 s:0214 e:000213 METHOD /bundle/ruby/2.7.0/gems/isotree-0.2.1/lib/isotree/isolation_forest.rb:47
c:0038 p:0012 s:0208 e:000207 BLOCK  /app/app/services/check/rate_outlier.rb:45 [FINISH]
c:0037 p:---- s:0204 e:000203 CFUNC  :tap
c:0036 p:0038 s:0200 e:000199 METHOD /app/app/services/check/rate_outlier.rb:44
c:0035 p:0005 s:0194 e:000193 METHOD /app/app/services/check/rate_outlier.rb:26
c:0034 p:0005 s:0188 e:000187 SEGV received in SEGV handler
Aborted
```
Doing the same on macos without docker works without issues.

Any hints to resolve this?

**Comment by ankane** [comment]
Hey @dup2, I'm not really sure of the cause, but if you can put together a minimal reproducible example, I can look into it more.

**Comment by dup2** [comment]
Hi @ankane, will try to do this.

I'm using this in a rails application and this seems to be the issue (or any other gem we are using).

Using it without rails seems to work without problems.

**Comment by dup2** [comment]
Found the issue - sorry for bothering you.

I had been using custom options for the `sample_size` and this worked for the "real data". When writing unit tests, we do not have a lot of data and in fact the test data used for fitting was smaller than `sample_size` which leads to a segmentation fault.

We can close this.

**Comment by ankane** [comment]
Pushed a fix so it no longer segfaults in that situation. Thanks for reporting!
